# Generated by Django 6.0.1 on 2026-02-04 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_created_at_user_email_verified_user_last_login_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Business Owner/Manager', 'Business Owner/Manager'), ('Branch Manager', 'Branch Manager'), ('Service Advisor/Staff', 'Service Advisor/Staff'), ('Inventory Manager', 'Inventory Manager')], max_length=50)),
                ('branch', models.CharField(max_length=100)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to='api.user')),
            ],
        ),
    ]
