# Generated by Django 6.0.1 on 2026-02-14 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_staff_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Business Owner/Manager', 'Business Owner/Manager'), ('Branch Manager', 'Branch Manager'), ('Service Advisor/Staff', 'Service Advisor/Staff'), ('Inventory Manager', 'Inventory Manager')], max_length=50),
        ),
    ]
