# Generated by Django 6.0.1 on 2026-02-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_staff_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Business Owner', 'Business Owner'), ('Branch Manager', 'Branch Manager'), ('Staff', 'Staff (Cashier)'), ('Employee', 'Employee (Mechanic)')], max_length=50),
        ),
    ]
