# Generated by Django 6.0.1 on 2026-03-09 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_staff_role'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='customers',
        ),
        migrations.AlterModelTable(
            name='staff',
            table='staffs',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
