# Generated by Django 6.0.1 on 2026-03-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_user_password_hash_user_groups_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='suffix',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='suffix',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
