# Generated by Django 6.0.1 on 2026-03-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_branch_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Business Owner', 'Business Owner'), ('Branch Manager', 'Branch Manager'), ('Staff', 'Staff (Cashier)'), ('Employee', 'Employee (Mechanic)'), ('Inventory', 'Inventory')], max_length=50),
        ),
    ]
