# Generated by Django 6.0.1 on 2026-03-16 04:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_staff_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('vehicle', models.CharField(blank=True, max_length=200)),
                ('plate_number', models.CharField(blank=True, max_length=50)),
                ('service', models.CharField(max_length=200)),
                ('branch', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('booking', 'Booking'), ('walk_in', 'Walk-in')], default='walk_in', max_length=20)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('in_service', 'In Service'), ('done', 'Done'), ('skipped', 'Skipped')], default='waiting', max_length=20)),
                ('position', models.PositiveIntegerField(default=0)),
                ('queued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('service_started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_entry', to='api.booking')),
            ],
            options={
                'db_table': 'queue_entries',
            },
        ),
    ]
