# Generated by Django 6.0.1 on 2026-03-16 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_queueentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueentry',
            name='assigned_employee',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Employee'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_assignments', to='api.staff'),
        ),
        migrations.AlterField(
            model_name='queueentry',
            name='branch',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='queueentry',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='queueentry',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='queueentry',
            name='plate_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='queueentry',
            name='vehicle',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
