# Generated by Django 6.0.1 on 2026-03-18 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_queueentry_assigned_employee_alter_queueentry_branch_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='queueentry',
            options={'ordering': ['position', 'queued_at']},
        ),
        migrations.AddField(
            model_name='queueentry',
            name='branch_name',
            field=models.CharField(blank=True, default='', help_text='Legacy plain-text branch name. Use `branch` FK instead.', max_length=200),
        ),
        migrations.AddField(
            model_name='staff',
            name='branch_name',
            field=models.CharField(blank=True, default='', help_text='Legacy plain-text branch name. Kept for reference; use `branch` FK instead.', max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='queueentry',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_entries', to='api.branch'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='api.branch'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='api.booking')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='api.branch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='api.customer')),
            ],
            options={
                'db_table': 'ratings',
            },
        ),
    ]
