# Generated by Django 6.0.1 on 2026-03-19 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_customer_birthdate_customer_profile_picture_and_more'),
        ('api', '0014_fix_branch_name_duplicate'),
    ]

    operations = [
    ]
