# Generated by Django 6.0.1 on 2026-03-19 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_merge_20260319_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='suffix',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='suffix',
        ),
    ]
