# Generated by Django 6.0.1 on 2026-03-19 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_customer_birthdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Maintenance', 'Maintenance'), ('Repair', 'Repair'), ('Diagnostic', 'Diagnostic'), ('Cosmetic', 'Cosmetic')], max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('duration', models.CharField(blank=True, default='', max_length=50)),
                ('price_min', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_max', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branches', models.ManyToManyField(blank=True, related_name='services', to='api.branch')),
            ],
            options={
                'db_table': 'services',
            },
        ),
    ]
