# Generated by Django 6.0.1 on 2026-03-19 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Lubricants', 'Lubricants'), ('Brakes', 'Brakes'), ('Filters', 'Filters'), ('Batteries', 'Batteries'), ('Tires', 'Tires'), ('Ignition', 'Ignition'), ('Other', 'Other')], max_length=50)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('minimum_qty', models.PositiveIntegerField(default=0, help_text='Threshold for low stock alert')),
                ('unit', models.CharField(default='Pieces', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('supplier', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='api.branch')),
            ],
            options={
                'db_table': 'inventory_items',
            },
        ),
    ]
