# Generated by Django 6.0.1 on 2026-03-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_queueentry_payment_method_queueentry_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='suffix',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
