# Generated by Django 6.0.1 on 2026-03-19 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_customer_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueentry',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_entries', to='api.branch'),
        ),
    ]