# Generated by Django 6.0.1 on 2026-03-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_fix_branch_name_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueentry',
            name='branch_name',
            field=models.CharField(blank=True, default='', help_text='Legacy plain-text branch name. Use `branch` FK instead.', max_length=200),
        ),
    ]
