# Generated by Django 6.0.1 on 2026-03-22 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_booking_status'),
        ('api', '0027_inventorytransaction'),
    ]

    operations = [
    ]
