# Generated by Django 6.0.1 on 2026-03-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_merge_20260322_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancellation_reason',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
