# Generated by Django 6.0.1 on 2026-03-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_add_inventory_manager_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Business Owner', 'Business Owner'), ('Branch Manager', 'Branch Manager'), ('Staff', 'Staff (Cashier)'), ('Employee', 'Employee'), ('Inventory', 'Inventory'), ('Inventory Manager', 'Inventory Manager')], max_length=50),
        ),
    ]
