# Generated by Django 6.0.1 on 2026-03-31 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_alter_staff_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_type', models.CharField(max_length=50)),
                ('scope_type', models.CharField(max_length=30)),
                ('model_used', models.CharField(max_length=100)),
                ('period_type', models.CharField(max_length=20)),
                ('prediction_start_date', models.DateField(blank=True, null=True)),
                ('prediction_end_date', models.DateField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='success', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.branch')),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.inventoryitem')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.service')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryDemandForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_period_label', models.CharField(max_length=50)),
                ('predicted_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('historical_average_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('minimum_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('recommended_restock_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock_risk_level', models.CharField(default='normal', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.branch')),
                ('forecasting_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.forecastingrun')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.inventoryitem')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceDemandForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_period_label', models.CharField(max_length=50)),
                ('predicted_booking_count', models.IntegerField()),
                ('historical_average_count', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('predicted_queue_count', models.IntegerField(blank=True, null=True)),
                ('peak_load_flag', models.BooleanField(default=False)),
                ('staffing_suggestion', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.branch')),
                ('forecasting_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.forecastingrun')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceDurationPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('based_on_queue_volume', models.IntegerField(blank=True, null=True)),
                ('based_on_booking_volume', models.IntegerField(blank=True, null=True)),
                ('based_on_avg_duration_minutes', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_duration_minutes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_wait_minutes', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.branch')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.staff')),
                ('forecasting_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.forecastingrun')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.service')),
            ],
        ),
    ]
