# Generated by Django 6.0.1 on 2026-03-31 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_alter_staff_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reschedule_request_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
