# Generated by Django 6.0.1 on 2026-03-31 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_booking_reschedule_request_reason'),
        ('api', '0044_forecastingrun_inventorydemandforecast_and_more'),
    ]

    operations = [
    ]
