# Generated by Django 6.0.1 on 2026-04-01 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_merge_20260401_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('Super Admin', 'Super Admin'), ('Admin', 'Admin'), ('Business Owner', 'Business Owner'), ('Branch Manager', 'Branch Manager'), ('Staff', 'Staff (Cashier)'), ('Employee', 'Employee'), ('Inventory', 'Inventory'), ('Inventory Manager', 'Inventory Manager')], max_length=50),
        ),
    ]
