# Generated by Django 6.0.1 on 2026-04-01 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_alter_staff_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('Admin', 'Admin'), ('Business Owner', 'Business Owner'), ('Branch Manager', 'Branch Manager'), ('Staff', 'Staff (Cashier)'), ('Employee', 'Employee'), ('Inventory', 'Inventory'), ('Inventory Manager', 'Inventory Manager')], max_length=50),
        ),
    ]
