# Generated by Django 6.0.1 on 2026-04-01 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_alter_staff_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorydemandforecast',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.branch'),
        ),
        migrations.AlterField(
            model_name='servicedemandforecast',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.branch'),
        ),
        migrations.AlterField(
            model_name='servicedurationprediction',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.branch'),
        ),
    ]
