# Generated by Django 6.0.1 on 2026-04-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0049_landingcontent"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="target_path",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
