# Generated by Django 6.0.1 on 2026-04-01 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_notification_target_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='media_assets/')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('other', 'Other')], default='image', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'media_asset',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
