# Generated by Django 6.0.1 on 2026-04-04 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_branch_fb_url_branch_latitude_branch_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('employee', 'Employee'), ('customer', 'Customer')], max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('queue_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.queueentry')),
                ('sender_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'service_messages',
                'ordering': ['created_at'],
            },
        ),
    ]
