# Generated by Django 6.0.1 on 2026-04-03 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_mediaasset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='Unique identifier for the plugin', max_length=100, unique=True)),
                ('description', models.TextField()),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('author', models.CharField(blank=True, default='', max_length=100)),
                ('website', models.URLField(blank=True, default='')),
                ('category', models.CharField(choices=[('analytics', 'Analytics & Tracking'), ('notifications', 'Notifications & Alerts'), ('integrations', 'Third-party Integrations'), ('automation', 'Automation'), ('reporting', 'Reporting & Analytics'), ('payment', 'Payment Gateways'), ('marketing', 'Marketing Tools'), ('other', 'Other')], default='other', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('installed', 'Installed (Disabled)'), ('needs_update', 'Needs Update'), ('error', 'Error')], default='inactive', max_length=20)),
                ('is_system', models.BooleanField(default=False, help_text='System plugins cannot be uninstalled')),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Plugin-specific settings')),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('dependencies', models.JSONField(blank=True, default=list, help_text='List of plugin slugs required')),
                ('conflicts', models.JSONField(blank=True, default=list, help_text='List of plugin slugs that conflict')),
                ('accessible_by_roles', models.JSONField(blank=True, default=list, help_text='List of staff roles that can manage this plugin')),
                ('installed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installed_plugins', to='api.staff')),
            ],
            options={
                'db_table': 'plugins',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PluginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('install', 'Installed'), ('uninstall', 'Uninstalled'), ('activate', 'Activated'), ('deactivate', 'Deactivated'), ('update', 'Updated'), ('error', 'Error'), ('config_change', 'Configuration Changed')], max_length=20)),
                ('message', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plugin_actions', to='api.staff')),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.plugin')),
            ],
            options={
                'db_table': 'plugin_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
