# Generated by Django 6.0.1 on 2026-04-05 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_branch_fb_url_branch_latitude_branch_longitude_and_more'),
        ('api', '0053_add_default_plugins'),
    ]

    operations = [
    ]
