# Generated by Django 6.0.1 on 2026-04-07 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_servicemessage'),
        ('api', '0054_merge_20260405_1014'),
    ]

    operations = [
    ]
