# Generated by Django 6.0.1 on 2026-04-11 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_customersetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general', models.JSONField(blank=True, default=dict, help_text="Keys: siteName, siteTagline, siteMode ('live'|'maintenance'), maintenanceMessage, defaultLanguage, defaultTimezone, supportUrl")),
                ('email', models.JSONField(blank=True, default=dict, help_text='Keys: mailHost, mailPort, mailFrom, supportEmail, emailVerificationRequired, welcomeEmailEnabled')),
                ('security', models.JSONField(blank=True, default=dict, help_text='Keys: requireStrongPasswords, sessionTimeoutMinutes, maxLoginAttempts, lockoutDurationMinutes, allowTwoFactor, allowGoogleOAuth, allowFacebookOAuth')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'system_settings',
            },
        ),
    ]
