# Generated by Django 6.0.1 on 2026-04-10 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='vehicle_size',
            field=models.CharField(blank=True, choices=[('motor', 'Motorcycle'), ('small', 'Small (Sedan/Hatchback)'), ('medium', 'Medium (Crossover/SUV)'), ('large', 'Large (Van/Pickup)'), ('xl', 'Extra Large (Commercial/Bus)')], default='small', max_length=20),
        ),
    ]
