# Generated by Django 6.0.1 on 2026-04-11 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_systemsettings'),
        ('api', '0061_booking_vehicle_size'),
    ]

    operations = [
    ]
