# Generated by Django 6.0.1 on 2026-04-11 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_merge_0059_systemsettings_0061_booking_vehicle_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueentry',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('motor', 'Motorcycle'), ('small', 'Small (Sedan/Hatchback)'), ('medium', 'Medium (Crossover/SUV)'), ('large', 'Large (Van/Pickup)'), ('xl', 'Extra Large (Commercial/Bus)')], default='', max_length=20),
        ),
    ]
