# Generated by Django 6.0.1 on 2026-04-12 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_seed_default_plugins'),
        ('api', '0068_reportrun'),
    ]

    operations = [
    ]
