# Generated by Django 6.0.1 on 2026-08-31 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_merge_0066_seed_default_plugins_0068_reportrun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaasset',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('other', 'Other')], default='image', max_length=20),
        ),
    ]
