# Generated by Django 6.0.1 on 2026-09-03 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_alter_mediaasset_media_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiclePMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage', models.FloatField(default=0.0)),
                ('vehicle_name', models.CharField(default='My Vehicle', max_length=150)),
                ('vehicle_size', models.CharField(default='small', max_length=50)),
                ('plate_number', models.CharField(blank=True, max_length=20, null=True)),
                ('health_score', models.IntegerField(default=100)),
                ('status_label', models.CharField(default='Good Condition', max_length=50)),
                ('target_milestone_km', models.IntegerField(default=5000)),
                ('target_milestone_title', models.CharField(default='5,000 KM Minor PMS Checkup', max_length=150)),
                ('km_remaining', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pms_logs', to='api.customer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pms_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vehicle_pms_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
